// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FieldInfo 顶层字段名与推断类型。
 */
export interface FieldInfo {
    "Name": string;

    /**
     * "string" | "number" | "bool" | "object" | "array" | "null" | "unknown"
     */
    "Type": string;
}
