// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as parse$0 from "../parse/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "../search/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelSearch 取消进行中的检索（无则空操作）。
 */
export function CancelSearch(fileID: string, tabID: string): $CancellablePromise<void> {
    return $Call.ByID(350477328, fileID, tabID);
}

/**
 * ClearRecentFiles 清空全部历史记录。
 */
export function ClearRecentFiles(): $CancellablePromise<void> {
    return $Call.ByID(671551859);
}

/**
 * CloseFile 关闭文件，取消其所有检索并释放索引与结果缓存；
 * 临时日志的临时文件一并删除。
 */
export function CloseFile(fileID: string): $CancellablePromise<void> {
    return $Call.ByID(4121632788, fileID);
}

/**
 * ExportMatches 把 tabId 的全部命中原始行写入用户选择的文件（JSONL，逐行原样，行尾统一 \n）。
 * 用户取消返回空路径且无错误。
 */
export function ExportMatches(fileID: string, tabID: string): $CancellablePromise<string> {
    return $Call.ByID(3437408745, fileID, tabID);
}

/**
 * GetFieldValues 返回字段的取值枚举（字母序）。索引完成前阻塞等待；
 * 仅收集 string 值：字段不存在/非 string/取值过多截断时 Values 为空，
 * Truncated 标识截断（调用方据此回落为自由输入）。
 */
export function GetFieldValues(fileID: string, field: string): $CancellablePromise<$models.FieldValues> {
    return $Call.ByID(1305720140, fileID, field);
}

/**
 * GetFields 返回探测到的顶层字段（索引完成后才完整，未完成则阻塞等待）。
 */
export function GetFields(fileID: string): $CancellablePromise<parse$0.FieldInfo[] | null> {
    return $Call.ByID(2932512447, fileID);
}

/**
 * GetIndexStatus 查询索引进度（供前端打开文件后对账，事件为主、此方法兜底）。
 */
export function GetIndexStatus(fileID: string): $CancellablePromise<$models.IndexStatus> {
    return $Call.ByID(2161783016, fileID);
}

/**
 * GetLines 浏览模式：按行号取一页原始行。
 */
export function GetLines(fileID: string, start: number, count: number): $CancellablePromise<$models.PageResult> {
    return $Call.ByID(1553650857, fileID, start, count);
}

/**
 * GetPage 检索模式翻页：命中行号内存跳转，pageSize 由前端选择器决定。
 */
export function GetPage(fileID: string, tabID: string, page: number, pageSize: number): $CancellablePromise<$models.PageResult> {
    return $Call.ByID(3597592729, fileID, tabID, page, pageSize);
}

/**
 * ListRecentFiles 返回历史文件记录（最近打开在前），并探测文件在磁盘上是否仍存在。
 */
export function ListRecentFiles(): $CancellablePromise<$models.RecentFile[] | null> {
    return $Call.ByID(4045825588);
}

/**
 * OpenFile 打开指定路径文件（展示名 = 文件名）。同一路径已打开时复用现有会话，
 * 避免重复占用索引内存；同名但不同目录的文件是两个独立会话。
 */
export function OpenFile(path: string): $CancellablePromise<$models.FileInfo> {
    return $Call.ByID(4260092432, path);
}

/**
 * OpenFileDialog 弹出系统文件选择对话框并打开所选文件；用户取消返回空 FileInfo。
 */
export function OpenFileDialog(): $CancellablePromise<$models.FileInfo> {
    return $Call.ByID(816038336);
}

/**
 * OpenRecentFile 打开历史记录中的文件；文件已不在磁盘时返回明确错误，
 * 前端据此提示「文件不存在」并给出移除记录的选项。
 */
export function OpenRecentFile(id: number): $CancellablePromise<$models.FileInfo> {
    return $Call.ByID(2536471051, id);
}

/**
 * OpenTempLog 创建临时日志：内容写入系统临时目录后走与普通文件一致的解析/索引流程。
 * 上限：50,000 行 / 10 MiB（前端预检同口径，此处为准）。
 */
export function OpenTempLog(content: string): $CancellablePromise<$models.FileInfo> {
    return $Call.ByID(2653523862, content);
}

/**
 * RemoveRecentFile 从历史记录中移除一条（关闭文件不删记录，用户显式移除才删）。
 */
export function RemoveRecentFile(id: number): $CancellablePromise<void> {
    return $Call.ByID(185044095, id);
}

/**
 * RemoveTab 关闭检索 tab：取消进行中的扫描并释放该 tab 的命中缓存
 * （补充于 §8.1：关 tab 只取消会残留命中行号缓存，多 tab 高频增删会放大内存）。
 */
export function RemoveTab(fileID: string, tabID: string): $CancellablePromise<void> {
    return $Call.ByID(586894769, fileID, tabID);
}

/**
 * Search 提交检索（tabID 由前端生成），后台顺序扫描；期间 emit searchProgress。
 * pageSize 决定首屏返回行数；取消时返回 context 取消错误（前端静默处理）。
 */
export function Search(fileID: string, tabID: string, query: search$0.Query, pageSize: number): $CancellablePromise<$models.SearchResult> {
    return $Call.ByID(3669909110, fileID, tabID, query, pageSize);
}
