// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FieldValues 某字段探测到的取值枚举（供检索条件下拉，仅 string 类型字段有）。
 * Truncated=true 表示取值过多已截断：Values 为空，UI 应回落为自由输入。
 */
export interface FieldValues {
    "Field": string;
    "Values": string[] | null;
    "Truncated": boolean;
}

export interface FileInfo {
    "ID": string;
    "Path": string;
    "Name": string;

    /**
     * "indexing" | "ready" | "error"
     */
    "Status": string;
    "TotalLines": number;
}

export interface IndexProgressEvent {
    "FileID": string;
    "Percent": number;
    "Done": boolean;

    /**
     * 索引失败信息（成功为空）
     */
    "Error": string;
}

export interface IndexStatus {
    "FileID": string;
    "Done": boolean;

    /**
     * 0~100
     */
    "Percent": number;
    "Error": string;
}

export interface PageResult {
    "Total": number;
    "Rows": ParsedLine[] | null;
}

export interface ParsedLine {
    "LineNo": number;
    "Raw": string;
    "Valid": boolean;

    /**
     * 非法行为 nil
     */
    "JSON": { [_ in string]?: any } | null;

    /**
     * unix 毫秒
     */
    "Timestamp": number | null;
    "Level": string;
    "Message": string;
}

export interface SearchProgressEvent {
    "FileID": string;
    "TabID": string;
    "Scanned": number;
    "Total": number;
    "Done": boolean;
}

export interface SearchResult {
    "TabID": string;
    "Total": number;

    /**
     * 第一页
     */
    "Rows": ParsedLine[] | null;
}
