// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CacheEntryInfo 一条本地缓存条目（缓存管理界面用）。
 */
export interface CacheEntryInfo {
    "SourceKey": string;

    /**
     * user@host:port
     */
    "Remote": string;
    "Path": string;
    "Name": string;
    "Size": number;

    /**
     * unix 毫秒
     */
    "LastUsedAt": number;

    /**
     * 当前有会话在使用（清除时会被跳过）
     */
    "InUse": boolean;
}

/**
 * CacheInfo 缓存总览。
 */
export interface CacheInfo {
    /**
     * 全局开关（主机可以再单独覆盖）
     */
    "Enabled": boolean;

    /**
     * 数据库可用、缓存功能才可用
     */
    "Available": boolean;
    "Dir": string;

    /**
     * 总量上限（字节；<=0 表示不限制）
     */
    "Limit": number;
    "TotalBytes": number;
    "Entries": CacheEntryInfo[] | null;
}

/**
 * Connection 一台已保存的远端主机。
 * 
 * 注意：**口令不回传前端**。Connection 里只有 HasPassword（是否已保存），
 * 连接时由后端自动取用库里保存的明文口令（见 ConnectRemote）。
 * 这样明文只存在于数据库与 Go 进程内存，不会多一份进 WebView。
 */
export interface Connection {
    "ID": number;
    "Name": string;
    "Host": string;
    "Port": number;
    "User": string;

    /**
     * "password" | "key"
     */
    "AuthMethod": string;

    /**
     * 私钥文件路径（认证方式为 key 时）
     */
    "KeyPath": string;

    /**
     * Cache 该主机是否启用本地内容缓存；null = 跟随全局设置。
     */
    "Cache": boolean | null;

    /**
     * HasPassword 该主机是否已保存口令（登录密码或私钥口令），编辑表单据此提示「留空则沿用」。
     */
    "HasPassword": boolean;

    /**
     * 上次浏览的目录（再次打开浏览器时定位到这里）
     */
    "LastDir": string;

    /**
     * unix 毫秒
     */
    "LastUsedAt": number;

    /**
     * 当前是否有活动连接
     */
    "Connected": boolean;
}

/**
 * Credential 本次连接使用的口令。
 * 留空表示「沿用库里已保存的口令」；填了则在连接成功后覆盖保存。
 */
export interface Credential {
    /**
     * 登录密码（认证方式为 password 时）
     */
    "Password": string;

    /**
     * 私钥口令（私钥未加密时留空）
     */
    "Passphrase": string;
}

/**
 * FieldValues 某字段探测到的取值枚举（供检索条件下拉，仅 string 类型字段有）。
 * Truncated=true 表示取值过多已截断：Values 为空，UI 应回落为自由输入。
 */
export interface FieldValues {
    "Field": string;
    "Values": string[] | null;
    "Truncated": boolean;
}

export interface FileInfo {
    "ID": string;
    "Path": string;
    "Name": string;

    /**
     * "indexing" | "ready" | "error"
     */
    "Status": string;
    "TotalLines": number;

    /**
     * "local" | "remote"
     */
    "Kind": string;

    /**
     * 远端连接标识 user@host:port（本地为空）
     */
    "Remote": string;

    /**
     * 远端连接 id（本地为 0）
     */
    "ConnID": number;
}

export interface IndexProgressEvent {
    "FileID": string;
    "Percent": number;
    "Done": boolean;

    /**
     * 索引失败信息（成功为空）
     */
    "Error": string;

    /**
     * TotalLines 索引完成后的总行数（未完成时为 0）。行数只有在索引扫描结束后才可知，
     * 打开接口返回的 FileInfo.TotalLines 恒为 0，前端以此事件/GetIndexStatus 补正。
     */
    "TotalLines": number;
}

export interface IndexStatus {
    "FileID": string;
    "Done": boolean;

    /**
     * 0~100
     */
    "Percent": number;
    "Error": string;

    /**
     * TotalLines 索引完成后的总行数（未完成时为 0）。供前端对账兜底：
     * 事件可能早于订阅就绪，行数靠这里补齐（FileInfo 是打开瞬间的快照，行数恒为 0）。
     */
    "TotalLines": number;
}

export interface PageResult {
    "Total": number;
    "Rows": ParsedLine[] | null;
}

export interface ParsedLine {
    "LineNo": number;
    "Raw": string;
    "Valid": boolean;

    /**
     * 非法行为 nil
     */
    "JSON": { [_ in string]?: any } | null;

    /**
     * unix 毫秒
     */
    "Timestamp": number | null;
    "Level": string;
    "Message": string;
}

/**
 * RecentFile 历史记录项（侧栏「最近打开」列表）。
 * 同名不同路径靠 Path/Dir 区分，同名不同主机再靠 Remote 区分。
 */
export interface RecentFile {
    "ID": number;
    "Path": string;
    "Name": string;
    "Dir": string;

    /**
     * 最近一次索引完成后的行数（未知为 0）
     */
    "TotalLines": number;
    "OpenCount": number;

    /**
     * unix 毫秒
     */
    "LastOpenedAt": number;

    /**
     * 记录读取时磁盘上是否仍存在；false = 已丢失，UI 标记并可移除记录
     */
    "Exists": boolean;

    /**
     * "local" | "remote"
     */
    "Kind": string;

    /**
     * 远端连接标识 user@host:port
     */
    "Remote": string;

    /**
     * 远端连接 id（重连用）
     */
    "ConnID": number;

    /**
     * Connected 远端主机当前是否有活动连接。远端文件的存在性不在列表阶段探测
     * （列表不能因网络卡住），未连接时 UI 显示「未连接」而不是「已丢失」。
     */
    "Connected": boolean;
}

/**
 * RemoteEntry 远端目录项。
 */
export interface RemoteEntry {
    "Name": string;
    "Path": string;
    "IsDir": boolean;
    "Size": number;

    /**
     * unix 毫秒
     */
    "ModTime": number;

    /**
     * 权限展示，如 -rw-r--r--
     */
    "Mode": string;
}

/**
 * RemoteListing 一次目录浏览的结果。
 */
export interface RemoteListing {
    /**
     * 当前目录（POSIX 绝对路径）
     */
    "Path": string;

    /**
     * 上级目录；已在根目录时为空
     */
    "Parent": string;

    /**
     * 远端家目录（快捷跳转用）
     */
    "Home": string;
    "Entries": RemoteEntry[] | null;
}

export interface SearchProgressEvent {
    "FileID": string;
    "TabID": string;
    "Scanned": number;
    "Total": number;
    "Done": boolean;
}

export interface SearchResult {
    "TabID": string;
    "Total": number;

    /**
     * 第一页
     */
    "Rows": ParsedLine[] | null;
}
