// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FieldValues 某字段探测到的取值枚举（供检索条件下拉，仅 string 类型字段有）。
 * Truncated=true 表示取值过多已截断：Values 为空，UI 应回落为自由输入。
 */
export interface FieldValues {
    "Field": string;
    "Values": string[] | null;
    "Truncated": boolean;
}

export interface FileInfo {
    "ID": string;
    "Path": string;
    "Name": string;

    /**
     * "indexing" | "ready" | "error"
     */
    "Status": string;
    "TotalLines": number;
}

export interface IndexProgressEvent {
    "FileID": string;
    "Percent": number;
    "Done": boolean;

    /**
     * 索引失败信息（成功为空）
     */
    "Error": string;

    /**
     * TotalLines 索引完成后的总行数（未完成时为 0）。行数只有在索引扫描结束后才可知，
     * 打开接口返回的 FileInfo.TotalLines 恒为 0，前端以此事件/GetIndexStatus 补正。
     */
    "TotalLines": number;
}

export interface IndexStatus {
    "FileID": string;
    "Done": boolean;

    /**
     * 0~100
     */
    "Percent": number;
    "Error": string;

    /**
     * TotalLines 索引完成后的总行数（未完成时为 0）。供前端对账兜底：
     * 事件可能早于订阅就绪，行数靠这里补齐（FileInfo 是打开瞬间的快照，行数恒为 0）。
     */
    "TotalLines": number;
}

export interface PageResult {
    "Total": number;
    "Rows": ParsedLine[] | null;
}

export interface ParsedLine {
    "LineNo": number;
    "Raw": string;
    "Valid": boolean;

    /**
     * 非法行为 nil
     */
    "JSON": { [_ in string]?: any } | null;

    /**
     * unix 毫秒
     */
    "Timestamp": number | null;
    "Level": string;
    "Message": string;
}

/**
 * RecentFile 历史记录项（侧栏「最近打开」列表）。同名不同路径的文件靠 Path/Dir 区分。
 */
export interface RecentFile {
    "ID": number;
    "Path": string;
    "Name": string;
    "Dir": string;

    /**
     * 最近一次索引完成后的行数（未知为 0）
     */
    "TotalLines": number;
    "OpenCount": number;

    /**
     * unix 毫秒
     */
    "LastOpenedAt": number;

    /**
     * 记录读取时磁盘上是否仍存在；false = 已丢失，UI 标记并可移除记录
     */
    "Exists": boolean;
}

export interface SearchProgressEvent {
    "FileID": string;
    "TabID": string;
    "Scanned": number;
    "Total": number;
    "Done": boolean;
}

export interface SearchResult {
    "TabID": string;
    "Total": number;

    /**
     * 第一页
     */
    "Rows": ParsedLine[] | null;
}
