// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Condition 单条字段条件。
 */
export interface Condition {
    /**
     * 字段名
     */
    "Field": string;

    /**
     * "=" | "!=" | "contains" | ">" | "<"
     */
    "Op": string;

    /**
     * 比较值（字符串形式，数值匹配时转换）
     */
    "Value": string;
}

/**
 * Query 一次查询：conditions 之间 AND；keyword、timeRange 与 conditions 之间 AND。
 */
export interface Query {
    "Conditions": Condition[] | null;

    /**
     * 对整行原始文本做子串匹配
     */
    "Keyword": string;
    "TimeRange": TimeRange | null;
}

/**
 * TimeRange 时间范围（unix 毫秒，闭区间；nil 字段表示该侧无界）。
 */
export interface TimeRange {
    "From": number | null;
    "To": number | null;
}
